### ISSUE TITLE
Tables in FEATURES not well formatted in GitHub viewer

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pySHACL#1]
https://github.com/RDFLib/pySHACL/blob/master/FEATURES.md

**Comment by ashleysommer** [comment]
I know. Its a limitation of the github markdown renderer, it doesn't support MD tables.
There's a link at the top of the FEATURES file to display the file using a better MD renderer:
http://dynalon.github.io/mdwiki/#!https://raw.githubusercontent.com/RDFLib/pySHACL/master/FEATURES.md

It might be worth completely redoing the features matrix without tables, so it renders correctly in Github.

**Comment by nicholascar** [comment]
Fixed display- not a limitation of GitHub but headings missing space after hashes getting in the way of table markup parsing.

**Comment by ashleysommer** [comment]
Ah, thanks.
Fixed via https://github.com/RDFLib/pySHACL/commit/628eb554352bfd156da84cf176ccd802d06c6b4d
