### ISSUE TITLE
BIND clause not allowed in SPARQL shape

### ISSUE THREAD

**Issue by stefanbischof** [RDFLib/pySHACL#102]
I'm trying to use pySHACL to validate an RDF Data Cube and one of the SPARQL shapes is not working with pySHACL. The error message is:
```
Validator generated a Validation Failure result:
A SPARQL Constraint must not contain a VALUES clause.
```
The SPARQL shape  (see https://github.com/w3c/shacl/blob/master/shapes/datacube.shapes.ttl#L106):
```turtle
sh:sparql [
      rdfs:comment "IC-12. No duplicate observations" ;
      sh:message "No two qb:Observations in the same qb:DataSet may have the same value for all dimensions." ;
      sh:prefixes <http://topbraid.org/datacube> ;
      sh:select """SELECT $this
WHERE {
	{
		# For each pair of observations test if all the dimension values are the same
		SELECT (MIN(?equal) AS ?allEqual)
		WHERE {
			$this qb:dataSet ?dataset .
			?obs2 qb:dataSet ?dataset .
			FILTER (?obs1 != ?obs2)
			?dataset qb:structure/qb:component/qb:componentProperty ?dim .
			?dim a qb:DimensionProperty .
			$this ?dim ?value1 .
			?obs2 ?dim ?value2 .
			BIND( ?value1 = ?value2 AS ?equal)
		}
		GROUP BY $this ?obs2
	}
	FILTER( ?allEqual )
}""" ;
    ]
```
and the error message seems to come from here https://github.com/RDFLib/pySHACL/blob/48155756d14d607f4fe0ea049aa28f42c874e68d/pyshacl/helper/sparql_query_helper.py#L298-L300

The SPARQL shape does not contain a VALUES clause but a BIND clause. And BIND is not prohibited by the SHACL spec (see https://www.w3.org/TR/shacl/#pre-binding). Do you have an idea what's the problem here?

PS: just found out the SPARQL query has a bug, all occurrences of `?obs1` should be replaced by `$this`. But this bug should not be related to the BIND thing.

**Comment by ashleysommer** [comment]
Ok, I have a fix for the detection of VALUES, SERVICE, and MINUS clauses in SPAQRL where the line they're on is commented.

However I've come across a futher issue with that datacube shapes file. In particular, its use of Subqueries (nested SELECT statements) in its SPARQL queries violate the pre-binding rules as described in [SHACL Spec Appendex A: Pre-Binding SPARQL Variables](https://www.w3.org/TR/shacl/#pre-binding). Specifically:
>Subqueries must return all potentially pre-bound variables, except shapesGraph and currentShape which are optional 

The only other "potentiality pre-bound variable" (if you don't define any of your own) is `$this`. That means all subqueries must `SELECT` the variable `$this`. Eg, the SPARQL for rule "IC-17" should read:

```sql
SELECT $this
WHERE {
	{
		# Count number of other measures found at each point
		SELECT $this ?numMeasures (COUNT(?obs2) AS ?count)
		WHERE {
			{
				# Find the DSDs and check how many measures they have
				SELECT $this ?dsd (COUNT(?m) AS ?numMeasures)
				WHERE {
					?dsd qb:component/qb:componentProperty ?m.
					?m a qb:MeasureProperty .
				}
				GROUP BY ?dsd
			}
			# Observation in measureType cube
			$this qb:dataSet/qb:structure ?dsd;
				qb:dataSet ?dataset ;
				qb:measureType ?m1 .

			# Other observation at same dimension value
			?obs2 qb:dataSet ?dataset ;
				qb:measureType ?m2 .
			FILTER NOT EXISTS {
				?dsd qb:component/qb:componentProperty ?dim .
				FILTER (?dim != qb:measureType)
				?dim a qb:DimensionProperty .
				$this ?dim ?v1 .
				?obs2 ?dim ?v2.
				FILTER (?v1 != ?v2)
			}
		}
		GROUP BY $this ?numMeasures
		HAVING (?count != ?numMeasures)
	}
}
```

**Comment by stefanbischof** [comment]
Thank you, @ashleysommer, for the very quick fix and release! 
And also for following the bug in the QB shapes with Holger!

**Comment by ashleysommer** [comment]
@stefanbischof You're welcome. I'm glad there are users of PySHACL like yourself who are finding and reporting these bugs, to make the SHACL experience smoother for everyone.
