### ISSUE TITLE
Iterating through the validation messages

### ISSUE THREAD

**Issue by calina-c** [RDFLib/pySHACL#107]
Hi all! I looked for some sort of support system and scoured through the source code and the Internet before asking this. I also tried to infer the structure by debugging, but I couldn't see it through. Sorry if it's the wrong place to ask.

I'm interested in generating a list of errors based on my Validation Report, but I am unsure how to traverse the graph and/or iterate. Can I somehow get all the violation messages? Or, preferably, tuples of `(property_path, violation_message)`?

**Comment by ashleysommer** [comment]
Hi @calina-c 
The graph that PySHACL returns is generated according to the [SHACL Validation Report](https://www.w3.org/TR/shacl/#validation-report) chapter in the SHACL Specification. See that documentation for more information.

The structure looks like this:
```
[	a sh:ValidationReport ;
	sh:conforms false ;
	sh:result [
		a sh:ValidationResult ;
		sh:resultSeverity sh:Violation ;
		sh:focusNode ex:Bob ;
		sh:resultPath ex:age ;
		sh:value "twenty two" ;
		sh:resultMessage "ex:age expects a literal of datatype xsd:integer." ;
		sh:sourceConstraintComponent sh:DatatypeConstraintComponent ;
		sh:sourceShape ex:PersonShape-age ;
	] ;
	sh:result [
		a sh:ValidationResult ;
		sh:resultSeverity sh:Warning ;
		sh:focusNode ex:Sally ;
		sh:resultPath ex:name ;
		sh:value "Sally" ;
		sh:resultMessage "ex:name should be greater than 5 letters." ;
		sh:sourceConstraintComponent sh:StringLengthComponent ;
		sh:sourceShape ex:PersonShape-name ;
	]
] .
```

If you need any further information on how to iterate through this graph, then it is no longer a PySHACL issue, rather you could ask on the SHACL mailing list for general shacl-related concerns, or on in the RDFLib documentation for how to iterate graphs in Python.
