### ISSUE TITLE
CLI: -m option produces an exception

### ISSUE THREAD

**Issue by rmeissn** [RDFLib/pySHACL#11]
When using pyshacl with -m option, pyshacl reports a traceback about a ValueError: read of closed file.

```
### pyshacl -m -s shape.ttl data.ttl
Traceback (most recent call last):
  File "/usr/local/bin/pyshacl", line 71, in <module>
    is_conform, v_graph, v_text = validate(args.data, **validator_kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyshacl/validate.py", line 194, in validate
    rdf_format=shacl_graph_format)
  File "/usr/local/lib/python3.7/site-packages/pyshacl/util.py", line 176, in load_into_graph
    data = target.read()
ValueError: read of closed file
```

shape.ttl and data.ttl are valid files with valid shapes and RDF data.
When using `pyshacl -s shape.ttl data.ttl`- so without -m - pyshacl works as expected.

**Comment by ashleysommer** [comment]
@rmeissn 
Thanks for this report. I've found the problem, and have worked a fix for it.
I will release as `0.9.8.post1` shortly.

**Comment by ashleysommer** [comment]
Fixed by https://github.com/RDFLib/pySHACL/commit/452b4b7025f5bbc6d0b39e5c4b608b1e57e514cf
