### ISSUE TITLE
Why Python <3.10 ?

### ISSUE THREAD

**Issue by RinkeHoekstra** [RDFLib/pySHACL#112]
My install of pySHACL on Python 3.9 using Poetry fails because of the requirement that the Python version should be smaller than 3.10

https://github.com/RDFLib/pySHACL/blob/8773c8c971a5a77a462e0e9d5687ce6dc78f06b3/pyproject.toml#L56

While this could be a bug in Poetry (3.9 is clearly smaller than 3.10), I wonder what the need is for the <3.10 constraint. Looking at the 3.10 release notes (https://www.python.org/dev/peps/pep-0619/#id7) I don't immediately see anything that could be a breaking change.

**Comment by ashleysommer** [comment]
Hi @RinkeHoekstra 
The <3.10 requirement was in place for two reasons:
1) Until recently, Poetry had some weird issues installing dependencies in python 3.10
    * this was fixed with Poetry v1.1.11 in October
2) RDFLib did not support Python 3.10 until only this month
    * this was fixed with RDFLib release v6.1.1

While this does not explain why you're seeing issues with Python 3.9, I can tell you that the next version of PySHACL will not have the <3.10 requirement.

**Comment by ashleysommer** [comment]
@RinkeHoekstra 
This should be fixed in PySHACL v0.18.0 :+1:

**Comment by RinkeHoekstra** [comment]
Thanks!
