### ISSUE TITLE
Strings with language tags errantly trigger validation errors

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/pySHACL#116]
If a `PropertyShape` is declared with `sh:datetype xsd:string`, instance data with a string with a language tag will trigger a validation error, declaring the string to not be of type `xsd:string`.  This appears to be isolated to `sh:datatype` constraints; `sh:nodeKind` does not appear to influence this behavior.

I will be filing a PR in a moment to add a demonstration test, after getting an Issue number.

**Comment by ajnelson-nist** [comment]
[PR 117](https://github.com/RDFLib/pySHACL/pull/117) filed.

**Comment by ashleysommer** [comment]
Thanks for the report @ajnelson-nist 
I've been looking into this, and I think the issue might be more nuanced than it may seem at first glance.

The SHACL specification for `sh:datatype` states: 
> The datatype of a literal is determined following the datatype function of [SPARQL 1.1](https://www.w3.org/TR/sparql11-query/#func-datatype). A literal matches a datatype if the literal's datatype has the _same IRI_.

The SPARQL 1.1 datatype function states:
> Returns the datatype IRI of a literal.
> * If the literal is a typed literal, return the datatype IRI.
> * If the literal is a simple literal, return **xsd:string**
> * If the literal is literal with a language tag, return **rdf:langString**


So it appears, the `datatype` of a literal with a language tag is `rdf:langString`, not `xsd:string`.

And further to my looking into this, I find that `rdf:langString` is not a subclass of `xsd:string`, rather a subclass of `rdf:Literal`.
So if `rdf:langString` is a subclass of Literal, does that mean it implicitly has a literal dataclass of `xsd:string`? I'm not sure.

I will ask on the SHACL Discord channel for more information.

**Comment by ashleysommer** [comment]
I would suggest you could change your Shapes constraints to use a `sh:or` to be valid on `sh:datatype xsd:string` or `sh:datatype rdf:langString`. But I expect you'd need to do that in a lot of places, and is not very practical. And I don't remember if PySHACL even supports `rdf:langString` in `sh:datatype`. I will check that out.

**Comment by ashleysommer** [comment]
Ok, I confirmed with Holger, the logic is correct, and a Literal with a lang tag is _not_ an `xsd:string`. I will do some testing in pySHACL to ensure my handling of `xsd:langString` is correct so you can use that instead.

**Comment by ajnelson-nist** [comment]
I saw you reverted the test from PR 117.  I assume this was to not have a failing CI test added to the `master` branch, which is fine by me.  I'll file another PR to commit a passing version.

I tried modifying the test to use `rdf:langString`, but encountered a curiosity.  The [OWL 2 Syntax document, Section 4.3](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Strings) does not list `rdf:langString`.  Apparently, the resolution of this point of confusion was to introduce a string ~"super-type", `rdf:PlainLiteral`, in [this Recommendation](https://www.w3.org/TR/2012/REC-rdf-plain-literal-20121211/).

I appreciate `pySHACL` isn't a strictly-OWL project.  But, is there a reason to try to use `rdf:langString` over `rdf:PlainLiteral`?

Another PR's coming in a moment, with assertions of conformance state as my current understanding has they should be.

**Comment by ajnelson-nist** [comment]
Ah dear, I just came across `rdf:langString` being the datatype to use in this situation in SHACL: [Section 4.1.2](https://www.w3.org/TR/shacl/#DatatypeConstraintComponent).  And, `rdf:PlainLiteral` is not mentioned in the SHACL specification.

I suppose, from the SHACL perspective, that settles the matter of `langString` versus `PlainLiteral`.  I'll update the test in the PR now.

**Comment by ajnelson-nist** [comment]
One test still fails - when the source shape uses `rdf:langString`, but the literal has no language.  Is this a transparent behavior `pyshacl` is supposed to handle?

**Comment by ashleysommer** [comment]
>  Is this a transparent behavior pyshacl is supposed to handle?

Probably is. I doubt there is a SHACL test suite test case that handles that edge case. I'll see what I can do.

**Comment by ajnelson-nist** [comment]
Thank you.  Also, I apologize if I sounded presumptive earlier.  If my test asserts the wrong true/false value in this case, I'm fine with being wrong and switching it.  I just need to know what the correct behavior is so I can forward that to my community.

**Comment by ashleysommer** [comment]
Yes, looks like PySHACL is behaving correctly in this case.

Using `sh:datatype rdf:langString` on `"A string without a language"` should be `conforms == False`.

**Comment by ajnelson-nist** [comment]
Thank you for the clarification.  Once the CI runs, I think [PR 119](https://github.com/RDFLib/pySHACL/pull/119) is now ready to merge.

**Comment by ashleysommer** [comment]
@ajnelson-nist 
I just double checked with Holger. He mentioned this "string or langString" pattern for `sh:datatype` is so common, they introduced a constant for it in the dash ontology. You can use `owl:imports` to import the dash ontology into your Shape file, in order to use it.

```
ex:myShape a sh:NodeShape ;
  sh:property [
    sh:path ex:name ;
    sh:or dash:StringOrLangString 
  ] .
  
```

**Comment by ajnelson-nist** [comment]
Thank you for the tip!  Importing an ontology is a committee action in my community, so might not be a quick-fix to this issue.

Also, I apologize again for letting my excitement of a passing unit test get the better of me.  I look forward to the results of your inspection of the other behaviors.

**Comment by ajnelson-nist** [comment]
Thanks for the merge!  Do you have any outstanding reasons on your end to keep this Issue open?
