### ISSUE TITLE
Validating using a shacl graph

### ISSUE THREAD

**Issue by RichDijk** [RDFLib/pySHACL#12]
[Python 3.7.0, rdflib 4.2.2, pyshacl 0.9.8.post1]

I  am using a graph as shacl_graph shown below.

```
conforms, v_graph, v_text = validate(g, shacl_graph=g2,
                                     data_graph_format='turtle',
                                     shacl_graph_format='turtle',
                                     inference='rdfs', debug=True,
                                     serialize_report_graph=True)

Validation Report
Conforms: True
```

The g2 graph I use is the following:
```
@prefix hei: <http://hei.org/customer/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

hei:HeiAddressShape a sh:NodeShape ;
    sh:property [ rdfs:comment "Street constraint" ;
            sh:datatype xsd:string ;
            sh:minlength 30 ;
            sh:path hei:Ship_to_street ] ;
    sh:targetClass hei:Hei_customer .
```

Data validated is:
```
hei:hei_cust_1281 a hei:Sfg_customer ;
    rdfs:label "XYZHorecagroothandel" ;
    hei:Klant_nummer 1281 ;
    hei:Ship_to_City "Middenmeer" ;
    hei:Ship_to_postcode "1799 AB" ;
    hei:Ship_to_street "Industrieweg" 
```

The issue is when I pass a graph object no validation is done; passing the g2 validation graph as a string works fine. I did expect both options to work fine.

**Comment by ashleysommer** [comment]
@RichDijk 
You're right, it should definitely work by passing in a graph as the shacl_graph. I will look into it.

You might not know the answer, but did it work in previous versions before 0.9.8.post1? There were changes to the way the graph loading routine works in the latest version, which may have introduced this bug.

**Comment by ashleysommer** [comment]
@RichDijk I've done some testing and I cannot reproduce the problem you are seeing.

See this gist: https://gist.github.com/ashleysommer/13b6c765539d7ebff3fd25630470b88c
The two functions work the same, but one passes the datafile and shacl file in as strings and the other as graph objects, and as you can see they both return the same validation result

***NOTE*** I had to change a couple of things in your example for it to work.

1. Typo in shacl graph g2: `sh:minlength` should be `sh:minLength` with capital L
  - Without this fix, the shape validation does not apply the minLength rule, so the example passes where it should fail.
2. Missing prefixes in the RDF Data text.
  - `@prefix hei: <http://hei.org/customer/> .`
  - `@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .`
  - Without these, rdflib refuses to parse the snippet into a Graph.

**Comment by RichDijk** [comment]
The typo in sh:minlength was the issue; no issue in pyshacl! The prefixes where in my data; judged this to be irrelevant. I will supply this nex time.
I am using Jupyter Notebook that created some uncertainty for me; but it works fine apparently.  
To close did use the following to create the validation graph where the typo occurred:

> 
> from rdflib import URIRef, BNode, Literal, Graph, Namespace
> from rdflib.namespace import RDF, RDFS , OWL, XSD
> from rdflib.plugins import sparql
> 
> HEI = Namespace("http://hei.org/customer/")
> 
> g2 =  Graph()
> g2.bind('sh', SH)
> g2.bind('hei', HEI)
> 
> HeiAddressShape_Street_shape = BNode()
> g2.add((HeiAddressShape_Street_shape, RDFS.comment, Literal("Street constraint")))   
> g2.add((HeiAddressShape_Street_shape, SH.path, HEI.Ship_to_street))
> g2.add((HeiAddressShape_Street_shape, SH.minLength, Literal(30)))
> g2.add((HeiAddressShape_Street_shape, SH.datatype, XSD.string ))
>           
> g2.add((HEI.HeiAddressShape, RDF.type, SH.NodeShape))
> g2.add((HEI.HeiAddressShape, SH.targetClass, HEI.Hei_customer))
> g2.add((HEI.HeiAddressShape, SH.property, HeiAddressShape_Street_shape))
>
