### ISSUE TITLE
allow-warnings and allow-infos need a unit test

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/pySHACL#126]
[PR-121](https://github.com/RDFLib/pySHACL/pull/121) was supposed to enable a result of `sh:conforms true` if only `sh:Info`-level validation results were yielded.  A unit test wasn't included in the PR to confirm `--allow-infos` worked.  I also attempted to trigger `--allow-warnings` and didn't get an expected result.  A test needs to be provided to confirm both command-line flags work.

**Comment by ajnelson-nist** [comment]
The weekend's starting for me, but I'll try to get something posted Monday.  Apologies for the trouble.

**Comment by ajnelson-nist** [comment]
Glancing at the README, I see I forgot to update the "Front-page" documentation.  I'll pick that up in the resolving PR.

**Comment by ajnelson-nist** [comment]
@ashleysommer , PRs [127](https://github.com/RDFLib/pySHACL/pull/127) and [128](https://github.com/RDFLib/pySHACL/pull/128) are ready for your review.  When both are merged, I'm fine with closing this Issue.

You had said [in PR 121](https://github.com/RDFLib/pySHACL/pull/121#issuecomment-1027376753) that you were going to add corresponding flags with non-plural spellings.  Did you still intend to do that before releasing?

**Comment by ashleysommer** [comment]
@ajnelson-nist 
PySHACL v0.19.0 is released now with those two PRs incorporated. Can you please test and let me know if everything is working properly for you.

Fixed by #127
Fixed by #128
