### ISSUE TITLE
pySHACL uses deprecated distutils package

### ISSUE THREAD

**Issue by tcmitchell** [RDFLib/pySHACL#146]
When pySHACL is used with Python 3.10 a `DeprecationWarning` is raised in certain environments:

```
$ PYTHONWARNINGS=default::DeprecationWarning python3 test.py
/private/tmp/venv19/lib/python3.10/site-packages/pyshacl/monkey/__init__.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
pyshacl version 0.19.0
```

Deprecation warnings are muted by default, so this warning is not always seen.

[PEP 632 suggests](https://peps.python.org/pep-0632/#id13) using [setuptools](https://setuptools.pypa.io/en/latest/index.html) instead of distutils. On the [Porting from Distutils](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html) page the suggestion is to use [packaging.version.*](https://packaging.pypa.io/en/latest/version.html) instead of `distutils.version.*`.

**Comment by ashleysommer** [comment]
@tcmitchell PR #147 was included in today's release v0.19.1 Thanks
