### ISSUE TITLE
Express coverage results in README

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pySHACL#15]
Assume this requires the deployment of coverage.py or similar package? Assume that's not already implemented?

**Comment by ashleysommer** [comment]
@nicholascar Do you mean code coverage stats in the sense of what proportion of code is touched during testing? That is something I've had in mind for a while, I can include it in the next release.

**Comment by nicholascar** [comment]
Yes. Perhaps using [coverage.py](https://coverage.readthedocs.io/en/v4.5.x/)

**Comment by ashleysommer** [comment]
Pycharm has coverage.py capabilities built in, I'm just using that for now.
As part of the 0.9.9 release I've fixed some coverage issues, added a bunch more tests, and got reported coverage up to 84%.
I've manually added a coverage tag to the README with "84%" hardcoded in the tag. If we want a dynamically updating one, we will need to deploy the coverage test to an online service like Travis, where we can always point to the results of the most recent coverage test run.

**Comment by wrobell** [comment]
If the project recommends use of `pytest`, then it can show coverage after running unit tests. Just put  something like the following into the `setup.cfg` project
```
[pytest]
addopts=--cov=pyshacl

[coverage:report]
show_missing=1
partial_branches=1
```
