### ISSUE TITLE
compatibility with rdflib 6 ClosedNamespaces 6.1.1

### ISSUE THREAD

**Issue by jbkoh** [RDFLib/pySHACL#150]

**Comment by jbkoh** [comment]
Sorry, accidentally hit the create button before checking something. I was using an old pyshacl, which wasn't compatiable with rdflib 6.

**Comment by ashleysommer** [comment]
@jbkoh do you think it would be beneficial if I included a note in the README file, that specifies you need to use PySHACL v0.17.0+ if you are using RDFLib 6?
It is already in the PySHACL v0.17.0 release notes: https://github.com/RDFLib/pySHACL/releases
