### ISSUE TITLE
How to remove violation printing in pyshacl module ?

### ISSUE THREAD

**Issue by akshayaakshaya** [RDFLib/pySHACL#155]
Hi,

I'm using the pySHACL module to validate the data as given below,

conforms, results_graph, v_text = validate(response.text, shacl_graph=shapes_graph,
                                                       shacl_graph_format=shapes_file_format, debug=False,
                                                       serialize_report_graph="ttl")

But the code is printing the violations even after giving the debug=False. 

Is there any solution for removing it?

**Comment by ashleysommer** [comment]
Thanks for reporting this. It is likely a bug. I will look into this as part of the work on the next version of PySHACL. I'll update this thread with what I find.

**Comment by ashleysommer** [comment]
Hi, I'm sorry, I can't reproduce this. I've tested several different methods of running the code given, with debug=False, and every time there is no violations printed out.

Can you give some more information about your runtime environment? (Eg, Operating System, Python Version, RDFLib Version, PySHACL version, etc).
