### ISSUE TITLE
pySHACL 0.21 not yet on PyPI

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/pySHACL#177]
Hi @ashleysommer ,

I see that [0.21.0](https://github.com/RDFLib/pySHACL/releases/tag/v0.21.0) was released a few days ago.  But, this doesn't appear to be on PyPI yet.  Is there any reason for that?

**Comment by ashleysommer** [comment]
Appologies, I pushed the release to github, and pushed the new docker image to dockerhub, but must've missed the PyPI push. Thanks for the reminder @ajnelson-nist

**Comment by ashleysommer** [comment]
It is released on PyPI now.
