### ISSUE TITLE
sh:not inside sh:or

### ISSUE THREAD

**Issue by Johannesmaek** [RDFLib/pySHACL#179]
Hi there, 
I'm trying to implement validation where I'm applying a sh:not inside one shape. 
It works in the SHACL Playground  but it does not work with pyshacl: 

**Shape Graph:** 
```
@prefix dash: <http://datashapes.org/dash#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://mapping.example.com/> .
@prefix dc: <http://purl.org/dc/elements/1.1#> . 


:test
    a sh:NodeShape ;
    sh:targetClass <http://example.org/class1> ;
        sh:or (
            [sh:not 
                   [
		        a sh:PropertyShape ;
		        sh:path schema:identifier ;
		        sh:hasValue "YES" ;
	            ] 
            ]
            [
                  sh:path schema:size ;
                  sh:minLength 4 ;
            ]
            ) .
```

**Data Graph:**

```
@prefix dash: <http://datashapes.org/dash#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <http://mapping.example.com/> .
@prefix dc: <http://purl.org/dc/elements/1.1#> . 

<http://example.org/9> a <http://example.org/class1>;
  dc:title "Example9";
  schema:identifier "YES";
  schema:size "12345" .

<http://example.org/10> a <http://example.org/class1>;
  dc:title "Example10";
  schema:identifier "NO";
  schema:size "12345" .

<http://example.org/11> a <http://example.org/class1>;
  dc:title "Example11";
  schema:identifier "NO";
  schema:size "12" .

<http://example.org/12> a <http://example.org/class1>;
  dc:title "Example12";
  schema:identifier "YES";
  schema:size "123" .
```

My Validation code in python looks like this: 

```
from pyshacl import validate
from os import path

data_graph = \
    'path of dataGraph.ttl'
data_graph = path.abspath(data_graph)

shapes_graph = \
    'path of shapesGraph.ttl'
shapes_graph = path.abspath(shapes_graph)

conforms, v_graph, v_text = validate(data_graph,data_graph_format="ttl", shacl_graph=shapes_graph,shacl_graph_format="ttl", inference='rdfs',debug=True,advanced=True, 
                                     serialize_report_graph=True)
print(conforms)

```

Thanks for your help in advance.

**Comment by ajnelson-nist** [comment]
Double-check your data graph?  All of your `rdf:type` statements assign a string as the class, not an IRI.

**Comment by Johannesmaek** [comment]
> Double-check your data graph? All of your `rdf:type` statements assign a string as the class, not an IRI.

Should be updated now.

**Comment by ajnelson-nist** [comment]
```turtle
<http://example.org/9> a "<http://example.org/class1>";
  dc:title "Example9";
  schema:identifier "YES";
  schema:size "12345" .
```

That still assigns a string as the class.  It should read instead:

```turtle
<http://example.org/9> a <http://example.org/class1> ;
  dc:title "Example9";
  schema:identifier "YES";
  schema:size "12345" .
```

For context: without that fix, your shape won't apply because nothing matches the `sh:targetClass` selector.

**Comment by Johannesmaek** [comment]
Sorry copied the wrong file. But that does not change the output. I still get the same violation as before and in SHACL Playground the one I was aiming for.

**Comment by Johannesmaek** [comment]
`Constraint Violation in HasValueConstraintComponent (http://www.w3.org/ns/shacl#HasValueConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]
        Focus Node: <http://example.org/11>
        Result Path: schema:identifier
        Message: Node <http://example.org/11>->schema:identifier does not contain a value in the set: ['Literal("YES")']

Constraint Violation in MinLengthConstraintComponent (http://www.w3.org/ns/shacl#MinLengthConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:minLength Literal("5", datatype=xsd:integer) ; sh:path schema:size ]
        Focus Node: <http://example.org/11>
        Value Node: Literal("12")
        Result Path: schema:size
        Message: String length not >= Literal("5", datatype=xsd:integer)

Constraint Violation in HasValueConstraintComponent (http://www.w3.org/ns/shacl#HasValueConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]
        Focus Node: <http://example.org/10>
        Result Path: schema:identifier
        Message: Node <http://example.org/10>->schema:identifier does not contain a value in the set: ['Literal("YES")']

Constraint Violation in NotConstraintComponent (http://www.w3.org/ns/shacl#NotConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:not [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ] ]
        Focus Node: <http://example.org/12>
        Value Node: <http://example.org/12>
        Message: Node <http://example.org/12> conforms to shape [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]

Constraint Violation in MinLengthConstraintComponent (http://www.w3.org/ns/shacl#MinLengthConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:minLength Literal("5", datatype=xsd:integer) ; sh:path schema:size ]
        Focus Node: <http://example.org/12>
        Value Node: Literal("123")
        Result Path: schema:size
        Message: String length not >= Literal("5", datatype=xsd:integer)

Constraint Violation in OrConstraintComponent (http://www.w3.org/ns/shacl#OrConstraintComponent):
        Severity: sh:Violation
        Source Shape: :test
        Focus Node: <http://example.org/12>
        Value Node: <http://example.org/12>
        Message: Node <http://example.org/12> does not conform to one or more shapes in [ sh:not [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ] ] , [ sh:minLength Literal("5", datatype=xsd:integer) ; sh:path schema:size ]

Constraint Violation in NotConstraintComponent (http://www.w3.org/ns/shacl#NotConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:not [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ] ]
        Focus Node: <http://example.org/9>
        Value Node: <http://example.org/9>
        Message: Node <http://example.org/9> conforms to shape [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]

False`

**Comment by Johannesmaek** [comment]
`
Constraint Violation in HasValueConstraintComponent (http://www.w3.org/ns/shacl#HasValueConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]
        Focus Node: <http://example.org/11>
        Result Path: schema:identifier
        Message: Node <http://example.org/11>->schema:identifier does not contain a value in the set: ['Literal("YES")']

Constraint Violation in MinLengthConstraintComponent (http://www.w3.org/ns/shacl#MinLengthConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:minLength Literal("5", datatype=xsd:integer) ; sh:path schema:size ]
        Focus Node: <http://example.org/11>
        Value Node: Literal("12")
        Result Path: schema:size
        Message: String length not >= Literal("5", datatype=xsd:integer)

Constraint Violation in HasValueConstraintComponent (http://www.w3.org/ns/shacl#HasValueConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]
        Focus Node: <http://example.org/10>
        Result Path: schema:identifier
        Message: Node <http://example.org/10>->schema:identifier does not contain a value in the set: ['Literal("YES")']

Constraint Violation in NotConstraintComponent (http://www.w3.org/ns/shacl#NotConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:not [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ] ]
        Focus Node: <http://example.org/12>
        Value Node: <http://example.org/12>
        Message: Node <http://example.org/12> conforms to shape [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]

Constraint Violation in MinLengthConstraintComponent (http://www.w3.org/ns/shacl#MinLengthConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:minLength Literal("5", datatype=xsd:integer) ; sh:path schema:size ]
        Focus Node: <http://example.org/12>
        Value Node: Literal("123")
        Result Path: schema:size
        Message: String length not >= Literal("5", datatype=xsd:integer)

Constraint Violation in OrConstraintComponent (http://www.w3.org/ns/shacl#OrConstraintComponent):
        Severity: sh:Violation
        Source Shape: :test
        Focus Node: <http://example.org/12>
        Value Node: <http://example.org/12>
        Message: Node <http://example.org/12> does not conform to one or more shapes in [ sh:not [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ] ] , [ sh:minLength Literal("5", datatype=xsd:integer) ; sh:path schema:size ]

Constraint Violation in NotConstraintComponent (http://www.w3.org/ns/shacl#NotConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:not [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ] ]
        Focus Node: <http://example.org/9>
        Value Node: <http://example.org/9>
        Message: Node <http://example.org/9> conforms to shape [ rdf:type sh:PropertyShape ; sh:hasValue Literal("YES") ; sh:path schema:identifier ]

False
`

**Comment by ashleysommer** [comment]
I haven't looked into this deeply, or run your example yet (I'm travelling today) but at first glance it appears to be working correctly to me.

Running with debug=True will cause pyshacl to output the result of every intermediate test, not only those that cause validation to be false. Run it with debug=False to see a cleaner output.

Example number 12 object in your example encounters a violation on both branches of the "sh:or" condition, that is why your final conformance result is False.

Looking at your debug output, you can see that particular data node fails the "sh:not" branch, and fails the "sh:minLength" branch, thus subsequently fails the "sh:or" constraint.

What result does SHACL playground give you?
