### ISSUE TITLE
Validating the domain (or ObjectProperty range) asserted in a data graph exists in the ontology graph?

### ISSUE THREAD

**Issue by tduval-unifylogic** [RDFLib/pySHACL#183]
Another question.

I would like to validate that the domain asserted in the data graph actually exists as a class specified in the ontology. I have successfully created validation for DatatypeProperty ranges:
```
    [ sh:path rdfs:range ; sh:nodetype sh:IRI ;
        sh:targetObjectsOf rdfs:range ;
        sh:in ( xsd:anyType xsd:anyURI xsd:base64Binary ...etc.  ) ;
    ] ,
```

but now i would like to be able to validate both domain and ranges existence for object properties.

**Comment by tduval-unifylogic** [comment]
sh:class owl:Class 

works perfect for my needs!

**Comment by tduval-unifylogic** [comment]
ah! thanks fo that!

**Comment by ashleysommer** [comment]
@tduval-unifylogic 
Is it OK to close this issue thread now?
