### ISSUE TITLE
cannot import name 'convert_graph' from 'owlrl'

### ISSUE THREAD

**Issue by ChrisGithubWork** [RDFLib/pySHACL#19]
Hey out there. 
I get a really confusing error while trying to set up pySHACL. 

I just try to import   `from pyshacl import validate`  in a python script and get the following error. 

```
Traceback (most recent call last):
  File ".\shaclCheck.py", line 1, in <module>
    from pyshacl import validate
  File "C:\Python37x64\lib\site-packages\pyshacl\__init__.py", line 3, in <module>
    from pyshacl.validate import validate, Validator
  File "C:\Python37x64\lib\site-packages\pyshacl\validate.py", line 5, in <module>
    import owlrl
  File "C:\Python37x64\Scripts\owlrl.py", line 4, in <module>
    from owlrl import convert_graph, RDFXML, TURTLE, JSON, AUTO, RDFA
ImportError: cannot import name 'convert_graph' from 'owlrl' (C:\Python37x64\Scripts\owlrl.py)
```

I think i did set up all Path variables related to the packages but i dont get this error fixed. 

My System is a Win10 set. I dont know if this does cause the problem?
Can somebody help me here? 

Best regards

**Comment by ashleysommer** [comment]
@ChrisGithubWork 
This is a an issue with OWL-RL, not with pySHACL.
I've gone ahead and created an issue in the OWL-RL issue tracker, here: https://github.com/RDFLib/OWL-RL/issues/29
I will close this issue.

**Comment by ChrisGithubWork** [comment]
@ashleysommer 
please close both issues. The problem was: I had owlrl allready installed with pip version 19.0.3 which comes with python 3.7 because i already worked with that. Now i installed pyshacl from inside an conda environement where python 3.55 and pip Version 18.0 is installed. So i think the Problem was a version error. After reinstalling both on one version it works now. 
Thank you for the quick response. 
Best regards
