### ISSUE TITLE
Shacl shapes

### ISSUE THREAD

**Issue by Remya-Ramachandran** [RDFLib/pySHACL#193]
Does pyshacl provide the functionality to generate SHACL shapes ?

**Comment by ashleysommer** [comment]
Hi @Remya-Ramachandran 
No, PySHACL is a SHACL validator. It has no capability to generate SHACL shapes.

**Comment by Remya-Ramachandran** [comment]
Hi @ashleysommer , appreciate your quick response. are you aware of any tools which can be used to generate SHACL shapes from ontology axioms.

**Comment by JoelBender** [comment]
Try [owl2shacl](https://github.com/sparna-git/owl2shacl).

**Comment by Remya-Ramachandran** [comment]
thanks
