### ISSUE TITLE
Multiple sh:xones on one sh:NodeShape grouping member shapes causing unexpected validation results

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/pySHACL#220]
I came across this when trying to write shapes for an OWL ontology that defines some classes as disjoint unions (covering sets) of multiple sets of classes.  For example, here is an analagous, distilled set of classes:

```turtle
@prefix ex: <http://example.org/ontology/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:OneXorThing
	a owl:Class ;
	owl:disjointUnionOf (
		ex:ThingA
		ex:ThingB
	) ;
	.

ex:ThingA
	a owl:Class ;
	rdfs:subClassOf ex:OneXorThing ;
	owl:disjointWith ex:ThingB ;
	.

ex:ThingB
	a owl:Class ;
	rdfs:subClassOf ex:OneXorThing ;
	owl:disjointWith ex:ThingA ;
	.

ex:ThingC
	a owl:Class ;
	rdfs:subClassOf ex:TwoXorThing ;
	owl:disjointWith ex:ThingD ;
	.

ex:ThingD
	a owl:Class ;
	rdfs:subClassOf ex:TwoXorThing ;
	owl:disjointWith ex:ThingC ;
	.

ex:ThingE
	a owl:Class ;
	rdfs:subClassOf ex:TwoXorThing ;
	owl:disjointWith ex:ThingF ;
	.

ex:ThingF
	a owl:Class ;
	rdfs:subClassOf ex:TwoXorThing ;
	owl:disjointWith ex:ThingE ;
	.

ex:TwoXorThing
	a owl:Class ;
	owl:disjointUnionOf
		(
			ex:ThingC
			ex:ThingD
		) ,
		(
			ex:ThingE
			ex:ThingF
		)
		;
	.

```

`ex:OneXorThing` is a covering set of two subclasses.  A member of `ex:OneXorThing` must be a member of exactly one of `ex:ThingA` or `ex:ThingB`.  `ex:TwoXorThing` functions similarly, but requires each of its members to members of two of two pairs of subclasses.

An aside: I found in a deeper dive through the OWL documentation that disjoint unions entail every assertion in that example OWL graph on the `ThingA`...`ThingF` classes, aside from `ex:ThingX a owl:Class.`.  The definition [here](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Disjoint_Union_of_Class_Expressions) describes the disjoint union class's member-classes as subclasses of the disjoint union class, albeit in English rather than demonstrated syntax: "Thus, each instance of C is an instance of exactly one CEi, and each instance of CEi is an instance of C."  This section is linked as the "Normative syntax" from the [OWL 2 New Features, Section 2.1.1 F1](https://www.w3.org/TR/2012/REC-owl2-new-features-20121211/#F1:_DisjointUnion).  I came across this when trying to determine if having more than one `owl:disjointWith` assertion on a class was disallowed somehow, and I believe I've exhausted the documentation and found nothing to disallow it.

Back to the distilled example: It seems to me that [`sh:xone`](https://www.w3.org/TR/shacl/#XoneConstraintComponent) lines up well as a reviewing mechanism for `owl:disjointUnion`, so I defined the following shapes graph, referenced further on as `sh-REPRODUCTION-2.ttl`:

```turtle
@prefix ex: <http://example.org/ontology/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix sh-ex: <http://example.org/shapes/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

sh-ex:OneXorThing-shape
	a sh:NodeShape ;
	sh:targetClass ex:TwoXorThing ;
	sh:xone (
		[
			a sh:NodeShape ;
			sh:class ex:ThingA ;
		]
		[
			a sh:NodeShape ;
			sh:class ex:ThingB ;
		]
	) ;
	.

sh-ex:TwoXorThing-shape
	a sh:NodeShape ;
	sh:targetClass ex:TwoXorThing ;
	sh:xone
		(
			[
				a sh:NodeShape ;
				sh:class ex:ThingC ;
			]
			[
				a sh:NodeShape ;
				sh:class ex:ThingD ;
			]
		) ,
		(
			[
				a sh:NodeShape ;
				sh:class ex:ThingE ;
			]
			[
				a sh:NodeShape ;
				sh:class ex:ThingF ;
			]
		)
		;
	.

```

I then used it to review the following data graph, referenced further on as `kb-REPRODUCTION-2.ttl`:

```turtle
@prefix ex: <http://example.org/ontology/> .
@prefix kb: <http://example.org/kb/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

kb:thing-PASS-1
	a ex:ThingA ;
	rdfs:comment "This should raise no validation results."@en ;
	.

kb:thing-PASS-2
	a
		ex:ThingC ,
		ex:ThingE
		;
	rdfs:comment "This should raise no validation results."@en ;
	.

kb:thing-XFAIL-1
	a ex:OneXorThing ;
	rdfs:comment "This should raise a validation result, due to not being more specifically a ThingA or ThingB as the SHACL requires when reviewing the OWL disjoint union definition of OneXorThing."@en ;
	.

kb:thing-XFAIL-2
	a ex:ThingC ;
	rdfs:comment "This should raise a validation result, due to not being a ThingE or ThingF as the SHACL requires when reviewing the entailed superclass TwoXorThing."@en ;
	.

```

I get the following shell transcript using pySHACL 0.25.0:

```
$ pyshacl \
  --metashacl \
  --ont-graph owl-REPRODUCTION.ttl \
  --shacl sh-REPRODUCTION-2.ttl \
  kb-REPRODUCTION-2.ttl
Validation Report
Conforms: False
Results (3):
Constraint Violation in XoneConstraintComponent (http://www.w3.org/ns/shacl#XoneConstraintComponent):
	Severity: sh:Violation
	Source Shape: sh-ex:TwoXorThing-shape
	Focus Node: kb:thing-XFAIL-2
	Value Node: kb:thing-XFAIL-2
	Message: Node kb:thing-XFAIL-2 does not conform to exactly one shape in [ rdf:type sh:NodeShape ; sh:class ex:ThingC ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingD ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingE ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingF ]
Constraint Violation in XoneConstraintComponent (http://www.w3.org/ns/shacl#XoneConstraintComponent):
	Severity: sh:Violation
	Source Shape: sh-ex:OneXorThing-shape
	Focus Node: kb:thing-PASS-2
	Value Node: kb:thing-PASS-2
	Message: Node kb:thing-PASS-2 does not conform to exactly one shape in [ rdf:type sh:NodeShape ; sh:class ex:ThingA ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingB ]
Constraint Violation in XoneConstraintComponent (http://www.w3.org/ns/shacl#XoneConstraintComponent):
	Severity: sh:Violation
	Source Shape: sh-ex:OneXorThing-shape
	Focus Node: kb:thing-XFAIL-2
	Value Node: kb:thing-XFAIL-2
	Message: Node kb:thing-XFAIL-2 does not conform to exactly one shape in [ rdf:type sh:NodeShape ; sh:class ex:ThingA ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingB ]
```

The two "XFAIL" individuals show in the validation results, which is what I want; but, one of the PASS individuals also shows up.  Further, it shows up in response to the wrong shape.  And the XFAIL error that I was trying to trigger with `kb:thing-XFAIL-2` reports an exactly-one-of list that looks flat, rather than like two pairs.

(Once I wrote that last sentence, I realized a problem with the data I'm reviewing is that my example individual is only a member of one of my disjoint unions, not both.  I got distracted looking at the apparent list-flattening.  But it is still an issue that `kb:thing-PASS-2` is triggering a test failure.)

If I reduce the shapes graph to only `sh-ex:TwoXorThing-shape`, and the data graph to only `kb:thing-PASS-2`, validation works.  But other combinations of removing shapes or individuals cause unexpected validation errors.  I've left a Makefile and the reductions I tried in [this Gist](https://gist.github.com/ajnelson-nist/67a126996c8c944246cb6365cc29d816) - it should run as documented in a fresh `git clone` in macOS or Linux.

**Comment by ashleysommer** [comment]
Hi @ajnelson-nist 
I've found some time to look into this.
Firstly, I fixed the issue you pointed out the message generation for Xone constraint (as seen in thing-XFAIL-2). It will now correctly show the pairs instead of a flat list (this was simply a string generation issue, not any problem with the validation results itself). 

Next, I see thing-PASS-2 is being validated according to the  sh-OneXorThing-shape because of a targeting error in your SHACL file. 
![image](https://github.com/user-attachments/assets/e9b63414-2170-440c-8781-85b3aaa2472e)
I believe that should have `targetClass` of `OneXorThing`.

After fixing that targeting error, I'm now seeing the expected results in the PySHACL output:
```
Validation Report
Conforms: False
Results (2):
Constraint Violation in XoneConstraintComponent (http://www.w3.org/ns/shacl#XoneConstraintComponent):
	Severity: sh:Violation
	Source Shape: sh-ex:OneXorThing-shape
	Focus Node: kb:thing-XFAIL-1
	Value Node: kb:thing-XFAIL-1
	Message: Node kb:thing-XFAIL-1 must conform to exactly one shape in [ rdf:type sh:NodeShape ; sh:class ex:ThingA ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingB ]
Constraint Violation in XoneConstraintComponent (http://www.w3.org/ns/shacl#XoneConstraintComponent):
	Severity: sh:Violation
	Source Shape: sh-ex:TwoXorThing-shape
	Focus Node: kb:thing-XFAIL-2
	Value Node: kb:thing-XFAIL-2
	Message: Node kb:thing-XFAIL-2 must conform to exactly one shape in ([ rdf:type sh:NodeShape ; sh:class ex:ThingC ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingD ]) and ([ rdf:type sh:NodeShape ; sh:class ex:ThingE ] , [ rdf:type sh:NodeShape ; sh:class ex:ThingF ])
```

**Comment by ajnelson-nist** [comment]
Ah, dear.  Good eye, I did indeed have a copy-paste error, and your fix addresses that part of this Issue.  I tried out the PR, and the reformatting clarifies the pairs.  Thank you!

**Comment by ashleysommer** [comment]
@ajnelson-nist 
PySHACL v0.27.0 was just released, with this fix and many others, and some new features.

**Comment by ajnelson-nist** [comment]
Thank you!
