### ISSUE TITLE
pySHACL 0.26.0 is not yet on PyPI

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/pySHACL#232]
I just noticed a fresh installation of pySHACL grabbed 0.25.0.  On checking PyPI, I see 0.26.0 isn't up there.

**Comment by ashleysommer** [comment]
Thanks for letting me know. I'll double check my release scripts, something might've gone wrong.

**Comment by ashleysommer** [comment]
Okay, I've uploaded the release to PyPI now, it might take a couple minutes to appear.

**Comment by ashleysommer** [comment]
Okay, I've uploaded the release to PyPI now, it might take a couple minutes to appear.

**Comment by ajnelson-nist** [comment]
Thank you!
