### ISSUE TITLE
shacl advanced features

### ISSUE THREAD

**Issue by sunyi000** [RDFLib/pySHACL#24]
Hi, 
I'm just trying to clarify if pySHACL support advanced features such as sh:target, sh:filterShapeNode etc? Looks like it doesn't support those properties currently..

Thanks,
Yi

**Comment by ashleysommer** [comment]
Hi @sunyi000

Yes, that's correct. The advanced features (including sh:target and sh:filterNodeShape) are being worked on, but not released yet.

At this time there is no expected completion timeframe or release date.

**Comment by ashleysommer** [comment]
Hi @sunyi000 
Good news, the sh:target advanced feature is now supported by the latest version of pySHACL (v0.10.0)
Feature as-of this commit https://github.com/RDFLib/pySHACL/commit/034b213a4fc7b1f96737e40c34096a568d5dd8fa

**Comment by sunyi000** [comment]
thanks very much @ashleysommer , that's really a good news.
I will try it out and post back if I have any questions or find any issues.

Thanks,
Yi
