### ISSUE TITLE
how do i validate a property which is an object?

### ISSUE THREAD

**Issue by sanuann** [RDFLib/pySHACL#25]
I have a jsonld data file which looks something like this:

       { "@type": "ex:Activity",
          "schema:description": "example schema",
          "ui": { "order": [
                      "john",
                      "mark",
                      "lisy" ],
               "shuffle": false }

How do I write a constraint for the property `ui` since it is an object?

**Comment by ashleysommer** [comment]
Hi @sanuann it looks like you have a question regarding writing a SHACL Constraint. That is not really a question or issue relating to the pySHACL project.
I suggest you look at the Shapes Constraint Language specification here: https://www.w3.org/TR/shacl/ 
There are a few different ways you can write the constraint you're describing above, I suggest you look at the [Property Shapes](https://www.w3.org/TR/shacl/#property-shapes) section, specifically the subsection about Property Paths.
