### ISSUE TITLE
Potentially wrong location of the `py.typed` file

### ISSUE THREAD

**Issue by s-heppner** [RDFLib/pySHACL#267]
Could it be that the `py.typed` file should actually be located in the `./pyshacl` directory? 
We've been having problems with `mypy` in our [CI-pipeline](https://github.com/eclipse-basyx/basyx-python-sdk/actions/runs/11194072665/job/31335542335?pr=308#step:5:46) of the PR: [eclipse-basyx/basyx-python-sdk#308](https://github.com/eclipse-basyx/basyx-python-sdk/pull/308): 

```
error: Skipping analyzing "pyshacl": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

I'm no expert on PEP 561 myself, but it seems in [this example](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages), the `py.typed` file is actually located on the same level as the top-level `__init__.py`.

**Comment by ashleysommer** [comment]
Thanks for this report. The py.typed file was added by another contributor a few years ago, and I assumed it was in the correct location. I'll look into if it needs to be changed.
