### ISSUE TITLE
Guidance request

### ISSUE THREAD

**Issue by teledyn** [RDFLib/pySHACL#28]
I've been happily using pyshacl (installed via pip3) to work on shacl rules, and in the process have broken my rules file in a manner I can't seem to correct, so was hoping you may have some tips for a newcomer ...

The error I get is simply
```
Validator encountered a Runtime Error:
Shape pointed to by sh:property does not exist or is not a well-formed SHACL PropertyShape.If you believe this is a bug in pyshacl, open an Issue on the pyshacl github page.
```
I don't believe it is a bug in pyshacl; the same two files in the shacl playground produce only `VALIDATION FAILURE: Missing subject` -- when I load the shacl into RDFlib and query, I can't find any `sh:property` triple with an unbound subject, but that may be a very naive approach.

run through meta-shacl shows nothing terribly helpful; unrelated things I know work in some engines such as using rdf:list items instead of spelling out a first/rest list.

In the -d debug trace, do the last few Constraint Report/Violations clues to the bad rule?
How might I get more information about what I've messed up in the shacl?

**Comment by ashleysommer** [comment]
Hi @teledyn 
It would help a lot if you were able to share a minimal version of your shapes file, so I can narrow in on your problem.

Unfortunately the error messages in pySHACL are not terribly helpful in these cases where there is something wrong with the shapes file, but you don't exactly know what it is. That is something I want to fix in the future, and issues such as this one you opened will to narrow down where more detailed reporting is required.

**Comment by ashleysommer** [comment]
@teledyn 
Do you still need assistance? If so, are you able to please share a version of your shapes file so I can debug your problem and find a solution for you?
