### ISSUE TITLE
Output with anonymous focus nodes, could it print whole node?

### ISSUE THREAD

**Issue by jameshowison** [RDFLib/pySHACL#32]
I'm doing some validation in data with anonymous nodes. The output of validate (e.g., results_text) shows:

```
Focus Node: [ ]
Value Node: [ ]
```

That makes it pretty hard to know which node has the issue.  Any thoughts on how to identify them.  I'm wondering if there could be an option to print either the datafile:line_number (hard, I know) or perhaps the whole anonymous node (ours are small, I know they could be very big, but even a few lines would probably help locate them).

**Comment by ashleysommer** [comment]
Hi, there is actually a standard feature in pyshacl which should print the whole anonymous node text in the output. If it's not doing that, it's a bug.

Are you able to share some sample code which reproduces this output?

**Comment by ashleysommer** [comment]
Hi Again, I think I have reproduced the same (or similar) problem in a new test I'm writing. I _think_ its yet another problem that was introduced when we switched from using Graphs by default to Datasets by default. Stringifying a blank node (anonymous node) that is in rdflib Dataset does not work in the same way as when using an rdflib Graph.

Working on a solution.

**Comment by ashleysommer** [comment]
Hi @jameshowison 
I pushed a fix for this bug, and is released as pySHACL v0.11.3, it should be available to installed from PyPI now.
Can you please check to see if the problem you described above is fixed in this new version.

**Comment by jameshowison** [comment]
Works perfectly now, shows whole anonymous node.  Apologies that I didn't include a specific reprex, will do next time!

(ps. and just a docker build --no-cache updated everything pulling the new version from PyPI).
