### ISSUE TITLE
Unexpected violation when using sh:qualifiedMinCount and sh:qualifiedValueShape

### ISSUE THREAD

**Issue by jameshowison** [RDFLib/pySHACL#33]
pyshacl is giving an unexpected violation, one that I'm not seeing on the javascript https://shacl.org/playground/ (and pyshacl is also not showing the sh:message of the only property).

Data:

```
@prefix ex: <http://example.org/ns#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:Document
    a schema:Document ;
    schema:isTargetOf  [ a schema:HasAuthor ;
                         schema:isPresent true ] ;
    schema:isTargetOf  [ a schema:otherClass ;
                         schema:isPresent true ] ;
.
```

shacl constraints

```
@prefix dash: <http://datashapes.org/dash#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

schema:DocumentShape
    a sh:NodeShape ;
    sh:targetClass schema:Document ;
    sh:property [
        sh:message "At least one Author" ;
        sh:path schema:isTargetOf ;
        sh:qualifiedMinCount 1 ;
        sh:qualifiedValueShape [
            sh:class schema:HasAuthor ;
        ]
    ] ;
.
```

Python code used:
```
import rdflib
from pyshacl import validate
data_filename = "data/shacl/example_data_value.ttl"
data_graph = rdflib.Graph()
data_graph.parse(data_filename, format='n3')

constraints_filename = "data/shacl/shacl_constraints_value.ttl"
constraints_graph = rdflib.Graph()
constraints_graph.parse(constraints_filename, format='n3')

r = validate(data_graph,
            shacl_graph=constraints_graph,
            # ont_graph=og,
             inference='rdfs', abort_on_error=False,
             meta_shacl=False, debug=True, advanced=True)
conforms, results_graph, results_text = r
conforms
```

What I'm seeing in the terminal (note the absence of the `sh:message`)
```
$ python3 data/shacl/validate_transition.py
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:class schema:HasAuthor ]
        Focus Node: [ rdf:type rdfs:Resource, schema:otherClass ; schema:isPresent Literal("true" = True, datatype=xsd:boolean) ]
        Value Node: [ rdf:type rdfs:Resource, schema:otherClass ; schema:isPresent Literal("true" = True, datatype=xsd:boolean) ]
```

**Comment by ashleysommer** [comment]
Hi @jameshowison.

There are three Shacl Shapes defined in that ShapesFile. There's the NodeShape called schema:DocumentShape, an anonymous PropertyShape on its `sh:property`, and an anonymous NodeShape given on the `sh:qualifiedValueShape` constraint.

You're not seeing a sh:message because the constraint that is failing is the ClassConstraint in the anonymous shape given on `sh:qualifiedValueShape`, and that shape doesnt have a sh:message.

The DocumentShape and it's property-shape are both still passing.

What is the value of the `conforms` variable after the validation result is returned? I believe it will be `True` becuse the qualifiedValueShape constraint still passes, and your data is still conformant.

You are seeing that extra violation in the command line output because you have `debug=True`, it will show all violations, even including the ones which do not cause your data to be non-conformant.

**Comment by jameshowison** [comment]
Spot on, that was the issue.  Indeed conforms was `true` once I printed it (that code was initially from a Notebook hence not having print on the last line).  Debug set to false removed that message.

I also tested by defining a Shape for the sh:qualifiedValueShape (so not an anonymous shape anymore). That removes the other warning.

```
schema:DocumentShape
    a sh:NodeShape ;
    sh:targetClass schema:Document ;
    sh:property [
        sh:message "At least one Author" ;
        sh:path schema:isTargetOf ;
        sh:qualifiedMinCount 1 ;
        sh:qualifiedValueShape schema:CodeShape ;
    ] ;
.

schema:CodeShape
    a sh:NodeShape ;
    sh:targetClass schema:HasAuthor ;
    sh:property [
        sh:message "code needs a single T/F value for schema:isPresent" ;
        sh:path schema:isPresent ;
        sh:datatype xsd:boolean ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
    ]
.
```

Anyway I turned debug off (since I don't need it :) but this was helpful anyway for me to understand what's happening in shacl :)
