### ISSUE TITLE
super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by alexiskeely** [RDFLib/pySHACL#35]
Updated the library to pull in some recent changes, and ran into this error: super(type, obj): obj must be an instance or subtype of type. The function below was running fine before the update. Any idea what could be causing this?

```
try: 
    conforms, v_graph, v_text = validate(places, shacl_graph=places_shape,
                                     data_graph_format=data_file_format,
                                     shacl_graph_format=shapes_file_format,
                                     inference='rdfs', debug=True,
                                     serialize_report_graph=True)
    print(conforms)
    
except Exception as e:
    print(e)
    pass
```

**Comment by ashleysommer** [comment]
Hi @alexiskeely,

Thanks for the report.

I'm afraid I'm going to have to ask you to provide some more context around exactly what parameters you are passing to the validate function.

That exact snippet works fine for me when testing, with the variables set to normal inputs. As well as all of the example files in the pyshacl examples directory still work normally and all of the SHACL test suite is still passing.

Having said that, there was some rather large changes to pyshacl in the last couple of versions, so theres a good chance that did introduce a breakage for whatever it is you are passing into the validator.

Are you able to narrow down exactly which is the last version that still works for you, and which is the first version where the error occurrs?

**Comment by alexiskeely** [comment]
@ashleysommer , I reinstalled the library and things are working again. The issue might have been coming from elsewhere, sorry for the confusion!

**Comment by ashleysommer** [comment]
Thanks for the update. Glad you got your situation resolved!
