### ISSUE TITLE
Does pySHACL support SHACL-JS?

### ISSUE THREAD

**Issue by aafrozza** [RDFLib/pySHACL#43]
Hello,

I noticed that pySHACL supports SHACL Advanced Features
(SPARQL).

I wonder if you also have to support the SHACL JavaScript Extensions (SHACL-JS)?

Best Regards,

Angelo

**Comment by ashleysommer** [comment]
Hello @aafrozza 

No, PySHACL doesn't support SHACL-JS. We are looking at possible implementation strategies, but I don't think there's much interest from users for this feature.

**Comment by randlea2** [comment]
I and my colleagues would be very interested in SHACL-JS support, as it would allow us to implement constraints based on fetching the vocabularies which are used within the data graph, such as correct domain and range definitions.

**Comment by nicholascar** [comment]
> I and my colleagues would be very interested

We encourage all community initiated Pull Requests!
