### ISSUE TITLE
Support for recursion

### ISSUE THREAD

**Issue by James-Hudson3010** [RDFLib/pySHACL#45]
According to the SHACL spec:

> The validation with recursive shapes is not defined in SHACL and is left to SHACL processor implementations. 

I was wondering if pySHACL has any plans to support recursive shapes or does it?

**Comment by ashleysommer** [comment]
Hi @James-Hudson3010 
Yes, as of pySHACL v0.11.4, it should already support recursive shapes.

V0.11.4 introduced ability for the validator to detect recursive shapes and prevent crashing when that occurrs. That said, there are no tests to ensure _all_ types of recursive shapes work.

Are you seeing recursive shapes not handled correctly?

**Comment by James-Hudson3010** [comment]
No. I was just asking the question as I did not see this laid out clearly in the documentation. Perhaps I missed it. I will close this issue. However, if there is a documentation issue, this issue could be used to track that instead.
