### ISSUE TITLE
Regular expression in sh:pattern not processed correctly

### ISSUE THREAD

**Issue by James-Hudson3010** [RDFLib/pySHACL#47]
I have the following:

```
graph_data = """
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sch:  <http://schema.org/> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix ex:  <http://example.org/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

ex:JohnDoe a ex:XXXX .
ex:JohnDoe ex:name "hello.txt" .
"""

shape_data = """
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sch:  <http://schema.org/> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix ex:   <http://example.org/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

ex:PersonShape
  a sh:NodeShape ;
  sh:targetClass ex:XXXX ;
  sh:property ex:PersonShape-name .

ex:PersonShape-name
  a sh:PropertyShape ;
  sh:path ex:name ;
  sh:minCount 1 ;
  sh:pattern  ".*.txt" .
"""
        
data  = rdflib.Graph().parse( data = graph_data, format = 'ttl' )
shape = rdflib.Graph().parse( data = shape_data, format = 'ttl' )

print( f"{data.serialize( format = 'ttl' ).decode( 'utf8' )}" )

report = validate( data, shacl_graph=shape, abort_on_error = False, meta_shacl = False, debug = True, advanced = True )

print( report[2] )
```

The ```sh:pattern``` should be ```".*\.txt"```, but when I do that, the following errors are generated:

``` 
... notation3.py", line 1591, in strconst  "bad escape")
... notation3.py", line 1615, in BadSyntax  raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)

  File "<string>", line unknown
BadSyntax
```

At least according to http://www.datypic.com/books/xquery/chapter19.html, I am using the escape correctly.

**Comment by debarghadas411** [comment]
This problem is not of pySHACL but rdfLib library as rdfLib processes the shape file into rdf graph and during that processing, it is decoding the regular expression which is essentially the problem you are referring to

**Comment by ashleysommer** [comment]
Hi @James-Hudson3010 
Sorry I didn't see this Issue come through, I only got notification when @debarghadas411 commented on it.
Yes, it is a problem with the .ttl parser in rdflib. Can you try this?:
`sh:pattern  ".*\\.txt" .`

**Comment by James-Hudson3010** [comment]
That does appear to work. 

It this a bug that should be reported to RDFLib then? Or, should this be considered expected behavior?

**Comment by debarghadas411** [comment]
I feel its a bug because `sh:pattern ".*\\.txt"` adds an extra escape character which should not be the case. sh:pattern should have a normal regular expression as object

**Comment by bhavya17037** [comment]
You can use another escape character after the '*'.
something like: 
`.*\\.txt`

**Comment by ashleysommer** [comment]
Issue was closed in pyshacl.
This is a turtle spec problem. and we can't change the turtle spec to allow new escape sequences.
The solution provided above is the correct solution for this problem.
