### ISSUE TITLE
Enable sh:pattern on IRIs

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pySHACL#52]
It is quite a common requirement to test an IRI to check if it is in a specific namespace, or contains a path element which is a specific character string or pattern. While the SHACL spec [appears to restrict application of `sh:pattern` to string literals](https://www.w3.org/TR/shacl/#PatternConstraintComponent), it would be helpful to allow a 'relaxed' mode where it can also apply to IRIs (which are, after all, just a [sequence of characters](https://tools.ietf.org/html/rfc3987)). 

Note that the TopBraid SHACL engine (maintained by the SHACL editor @HolgerKnublauch ) does operate in this mode - see https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/topbraid-users/BUoROZt0BhM

**Comment by ashleysommer** [comment]
I don't believe there is need for separate 'relaxed' mode for this change. Changing `sh:pattern` to work on IRIs as well as strings does not cause any of tests in the SHACL test suite to fail.

**Comment by dr-shorthair** [comment]
FWIW it looks like the TQ SHACL implementation is here: https://github.com/TopQuadrant/shacl

**Comment by HolgerKnublauch** [comment]
The spec is IMHO clear that IRIs can be checked too.

**Comment by ashleysommer** [comment]
@HolgerKnublauch 
Yes you're right. Re-reading the relevant sections I see it is pretty obvious. I think it was this part which threw me off:
>  The values of sh:pattern in a shape are literals with datatype xsd:string

I originally read that as "the focusnodes of sh:pattern are literals with datatype xsd:string" so thought it excluded IRIs.

However, just looking at implementing this feature in pySHACL I see it is already implemented. All string-based constraint operations already work on IRIs, and not by accident, there is even a method in there for all string-based constraints to turn an IRI to a string before evaluating.

So can close this as not a bug.

**Comment by dr-shorthair** [comment]
@HolgerKnublauch It is explicit on `sh:minLength` and `sh:maxLength` with the phrase "This can be applied to any literals and IRIs, but not to blank nodes.". Not explicit on `sh:pattern` (this briefly threw us off the trail), but not excluded either.
