### ISSUE TITLE
FocusNode and ValueNode in ReportGraph should be able to point to same BNode

### ISSUE THREAD

**Issue by ashleysommer** [RDFLib/pySHACL#57]
Related to #55
In building the report graph, when a valueNode and focusNode are both the same and are a Blank Node, the validation result's valueNode and focusNode will never have the same ID in the Report Graph. In the current implementation they are both copied over separately (thus they are two new blank nodes), but I could put a simple check if they are the same node, only copy it into the report graph once, then use that for both valueNode and focusNode, then they will have the same ID.

**Comment by michielhildebrand** [comment]
Great!

**Comment by ashleysommer** [comment]
Fixed by https://github.com/RDFLib/pySHACL/commit/50d56105df2f115ce7ad8abea19cc061248f75d2

**Comment by ashleysommer** [comment]
@michielhildebrand 
Can you test the new release v0.12.2 to see if it solves your Blank Node ID comparison use-case?
