### ISSUE TITLE
Parsing of json-ld datagraph fails with cli

### ISSUE THREAD

**Issue by nicholsn** [RDFLib/pySHACL#62]
I've been using pyshacl successfully with turtle documents (great to see how much progress is being made!), but I ran into an issue where pyshacl fails when reading a json-ld datagraph file from the cli with a `ValueError: seek of closed file`.

I'm using an example below from the SHACL Spec: https://www.w3.org/TR/shacl/#shacl-example. 

<details><summary>Here is the data graph (converted to json-ld)</summary>

<p>

### example_data.jsonld

```json
{
  "@context": {
    "ex": "http://example.org/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "ex:Calvin",
      "@type": "ex:Person",
      "ex:birthDate": {
        "@type": "xsd:date",
        "@value": "1971-07-07"
      },
      "ex:worksFor": {
        "@id": "ex:UntypedCompany"
      }
    },
    {
      "@id": "ex:Bob",
      "@type": "ex:Person",
      "ex:ssn": [
        "124-35-6789",
        "123-45-6789"
      ]
    },
    {
      "@id": "ex:Alice",
      "@type": "ex:Person",
      "ex:ssn": "987-65-432A"
    }
  ]
}
```

</p>

</details>

<details><summary>Here is the shape graph</summary>

<p>

### example_shape.jsonld

```json
{
	"@id" : "ex:PersonShape",
	"@type" : "NodeShape",
	"targetClass" : "ex:Person",
	"property" : [
		{
			"path" : "ex:ssn",
			"maxCount" : 1,
			"datatype" : "xsd:string" ,
			"pattern" : "^\\d{3}-\\d{2}-\\d{4}$"
		},
		{
			"path" : "ex:worksFor",
			"class" : "ex:Company",
			"nodeKind" : "sh:IRI"
		}
	],
	"closed" : true,
	"ignoredProperties" : [ "rdf:type" ]
}
```

</p>
</details>

<details><summary>Here is the command and error</summary>

<p>

```
$ pyshacl -sf json-ld -s example_shape.jsonld -df json-ld example_data.jsonld
Traceback (most recent call last):
  File "/Users/nnichols/Downloads/pyshacl/.pyshacl/bin/pyshacl", line 8, in <module>
    sys.exit(main())
  File "/Users/nnichols/Downloads/pyshacl/.pyshacl/lib/python3.7/site-packages/pyshacl/cli.py", line 159, in main
    is_conform, v_graph, v_text = validate(args.data, **validator_kwargs)
  File "/Users/nnichols/Downloads/pyshacl/.pyshacl/lib/python3.7/site-packages/pyshacl/validate.py", line 341, in validate
    data_graph = load_from_source(data_graph, rdf_format=data_graph_format, multigraph=True, do_owl_imports=False)
  File "/Users/nnichols/Downloads/pyshacl/.pyshacl/lib/python3.7/site-packages/pyshacl/rdfutil/load.py", line 305, in load_from_source
    source.seek(0)
ValueError: seek of closed file
```

</p>

</details>

Any thoughts what might be going on here? Am I missing something?

```
$ pyshacl --version
PySHACL Version: 0.13.2
```

**Comment by ashleysommer** [comment]
Hi @nicholsn 
Thanks for the bug report.

I made a small change to the way the rdf loading routine works in version 0.13.2, that may have caused this bug. I won't be able to investigate the cause for a few days.

In the meantime, are you able to try the same on pyshacl v0.13.0, v0.12.1.post2, and v0.11.6, to let me know if you see the same error?

**Comment by ashleysommer** [comment]
Update: nevermind. I've worked it out already. The cli runner of pyshacl opens the file paths automatically and passes fp objects into the validator. The validator uses a custom loader to pass the open fp objects to the correct parser to extract the rdf. The loader assumes that if the fp was open when it was passed in, then it should keep it open after parsing, (and as courtesy, seek back to pos 0 before exiting).
But the json-ld parser itself closes the fp when it is done. So when trying to seek to zero, it fails. That's why it only does it with json-ld format files.

I'm surprised this hasn't been reported before. This bug would've been in the code for around 12 months now. I guess not many people pass json-ld formatted code into the cli app.
Even all the cli-app tests in the pyshacl testsuite just use turtle files.

**Comment by nicholsn** [comment]
@ashleysommer thanks for the quick review and figuring out where the issue is. Let me know you want me to submit a PR to catch the `ValueError` this raises or if you have other ideas for how to patch this.

It is a bit surprising this didn't show up! My use case for json-ld is that I have users/anallysts not familiar with rdf and it allows me to hide away IRIs and term mappings behind a context file so to them it just looks like plan old json, but thanks to pyshacl I can generate nice conformance reports behind the scenes!
