### ISSUE TITLE
Could not install pyshacl using pip

### ISSUE THREAD

**Issue by RanjithSoman** [RDFLib/pySHACL#7]
I ma getting the following error when I try to install pyshacl

 Could not find a version that satisfies the requirement RDFClosure (from pyshacl) (from versions: )
No matching distribution found for RDFClosure (from pyshacl)

**Comment by RanjithSoman** [comment]
Solved it. Downloaded OWL-RL and executed 
 python setup.py install 
script in the directory.

**Comment by ashleysommer** [comment]
@RanjithSoman 
At the moment, RDFClosure (OWL-RL) is not available via the Python Package Index (pypi), so pySHACL installs it via a dependency-link. Unfortunately PIP does not install dependency-links of packages by default, so you need to install like this:

```
 pip3 install --process-dependency-links pyshacl 
```
I will add this to the README to avoid confusion for new users.
