### ISSUE TITLE
sh:not's severity defaults to sh:violation

### ISSUE THREAD

**Issue by chrdebru** [RDFLib/pySHACL#80]
Unless I have overlooked something, the SHACL spec does not state that the severity of a `sh:not` (a property shape) is by default `sh:violation`. Therefore, I would think that a `sh:not` with `sh:severity sh:Warning` should return warnings. That is not the case when testing with this minimal example below:

```
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix ex: <http://example.org/ex#> .

ex:Foo ex:prop1 "a" .

ex:FooShape
    sh:targetNode ex:Foo ;
    sh:not [
        a sh:PropertyShape ;
        sh:path ex:prop1 ;
        sh:hasValue "a" ;
        sh:severity sh:Warning ;
    ] ;
.
```

The output is:

```
$ pyshacl -s foo.ttl foo.ttl
Validation Report
Conforms: False
Results (1):
Constraint Violation in NotConstraintComponent (http://www.w3.org/ns/shacl#NotConstraintComponent):
        Severity: sh:Violation
        Source Shape: ex:FooShape
        Focus Node: ex:Foo
        Value Node: ex:Foo
        Message: Node ex:Foo conforms to shape [ rdf:type sh:PropertyShape ; sh:hasValue Literal("a") ; sh:path ex:prop1 ; sh:severity sh:Warning ]
```

**Comment by ashleysommer** [comment]
Hi @chrdebru 

I understand what you're asking, but I want to clarify some terminology.

`sh:not` is a constraint, not a Shape. A shape can have multiple constraints placed on it. A shape can have a severity, but a constraint cannot. In other words, if your data do not conform to the constraints imposed by the shape, then the validator emits a result with the severity given by that shape.

In your example, there is a PropertyShape with a `sh:hasValue` constraint and that shape has a severity of Warning.

**Comment by ashleysommer** [comment]
I know your example was a trivial minimal reproduction, but such a thing would normally be written with the severity logic in to top-level NodeShape like:

```
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix ex: <http://example.org/ex#> .

ex:Foo ex:prop1 "a" .

ex:FooShape
    sh:targetNode ex:Foo ;
    sh:severity sh:Warning ;
    sh:message "Foo must not have prop1 of 'a'";
    sh:not [
        a sh:PropertyShape ;
        sh:path ex:prop1 ;
        sh:hasValue "a" ;
    ] ;
.
```

**Comment by chrdebru** [comment]
Thanks for clarifying. I can confirm that Topbraid also "ignores" the severity on a not. 

Your argument is clear for the other logical constraint components. But the object of a `sh:not` is an instance of a shape: the range of `sh:not` is `sh:Shape` (https://www.w3.org/ns/shacl.ttl). You can add a severity on a property shape as follows:

```
ex:FooShape
    sh:targetNode ex:Foo ;
    sh:property [
        a sh:PropertyShape ;
        sh:path ex:prop1 ;
        sh:hasValue "a" ;
        sh:severity sh:Warning ;
    ] ;
.
```

And therefore I would assume the same would be possible for 

```
ex:FooShape
    sh:targetNode ex:Foo ;
    sh:not [
        a sh:PropertyShape ;
        sh:path ex:prop1 ;
        sh:hasValue "a" ;
        sh:severity sh:Warning ;
    ] ;
.
```

If I want to declare a severity only for that particular negated property shape, I have to declare a shape that has the `sh:not`, which seems to be very verbose for what I want to achieve.

Maybe that's a part of the spec that is underspecified. It could have easily stated that severities in logical constraint components (either directly as is the case for sh:not or via lists for the others) are "ignored". That also fixes the problem of a severity of a sh:not inside other logical operators.

**Comment by HolgerKnublauch** [comment]
The severities are all treated identical in the SHACL spec. I did not really understand why to be honest as Info shoukd not really block anything. Probably simpler this way, remaining binary.

**Comment by chrdebru** [comment]
I understand that these are purely informative, but that does not mean that their behaviors in more complex scenarios should not be specified.

**Comment by HolgerKnublauch** [comment]
But the spec already states that these values have no impact on validation. https://www.w3.org/TR/shacl/#severity

Nothing else needs to be said imho. These formal specs are generally very brief and compact.

**Comment by chrdebru** [comment]
Yes, they have no impact on the validation results, though the spec does describe its behavior for reporting (even if it's purely informative). But when their use/behavior is in certain cases underspecified and therefore left up to one's interpretation, then two implementations can report differently. If the property has no impact or purpose, then I would also question its inclusion. Specs should be brief and compact, but also complete. Or be explicit and state that certain aspects are left to an implementation's interpretation (as was done for a SPARQL DESCRIBE query in that Recommendation, for instance).

**Comment by HolgerKnublauch** [comment]
I believe we can agree to disagree on that. I see your point about specs being complete, but where would this stop. Should we for example mention that OWL inferencing has no impact, or that RIF has no impact or that sh:paths do not look at rdfs:subPropertyOf? The general rule is that if something is not mentioned then it has no impact.

The other issue is of course that the spec is fixed and cannot be updated anymore, without requiring a new 3-year working group. Topics such as explaining the use of sh:severity need to go into separate documents such as tutorials.

**Comment by chrdebru** [comment]
Okay, then it is up to an implementation's discretion and I can live with that. It is then up to the developers of pySHACL to decide.

**Comment by ashleysommer** [comment]
I'm considering implementing https://github.com/RDFLib/pySHACL/issues/64 ("Option to ignore warning") in pyshacl, to operate in an optional alternate mode where results with `sh:severity == sh:warning` would not be considered invalid data. That is a deviation from the SHACL spec, that states severity has no impact on validation results.

When operating in that alternate mode, then issues such as this one (sh:not severity) become more relevant.

With that said however, I believe there is no bug here. PySHACL behaves according to the SHACL specification in regard to emitting `sh:severity sh:violation` by default, and that can be changed by the user by setting an alternate `sh:severity` on the `NodeShape` as per the example above.
