### ISSUE TITLE
pySHACL 0.16.0 release timing

### ISSUE THREAD

**Issue by ajnelson-nist** [RDFLib/pySHACL#90]
Hello, @ashleysommer !  A community I'm working with ran into the issue [PR 88 fixed](https://github.com/RDFLib/pySHACL/pull/88) a couple weeks ago, and they came to the same diagnosis a day or two after @gtfierro filed PR 88.  We encountered the issue when doing final testing for an ontology version release.  Without the fix in PR 88, our community can't use SHACL to validate our most elementary examples, because our class hierarchy frequently has a depth of around 4 levels from `owl:Thing`.  We would like to be able to use the next version of pySHACL in our CI, pulling from PyPI.  I was wondering what other milestones, if any, you were waiting to meet before releasing 0.16.0.

**Comment by ashleysommer** [comment]
Hi @ajnelson-nist 
Great question. There was one more bug or feature I wanted to get done before pushing out the next release, but I don't know how long that will take (it might be a bit too ambitious).
So given the apparent popularity for this fix, I may just push out a release with just that, in the next day or two.
Thanks for contacting us.

**Comment by ashleysommer** [comment]
Ok, pushing out v0.16.0 today with just PR #88 change.

**Comment by ashleysommer** [comment]
[v0.16.0 released](https://github.com/RDFLib/pySHACL/releases/tag/v0.16.0).

**Comment by ajnelson-nist** [comment]
Many thanks!
