### ISSUE TITLE
Planned support for ExpressionConstraintComponent?

### ISSUE THREAD

**Issue by gtfierro** [RDFLib/pySHACL#91]
Hi there!

Are there any plans to support [`ExpressionConstraintComponent`s](https://www.w3.org/TR/shacl-af/#ExpressionConstraintComponent) (e.g. uses of `sh;expression`) in a future release of pySHACL? I found the [feature matrix](https://github.com/RDFLib/pySHACL/blob/master/FEATURES.md), but was unable to locate any roadmap or list of planned features.

No worries if it is not in any near-term plans; i may be able to attempt an implementation.

**Comment by ashleysommer** [comment]
Hi @gtfierro 
To be honest, I actually thought `ExpressionConstraintComponent` was already implemented. But as you pointed out, its not done yet and the Feature Matrix reflects that. You're the first user to notice its missing, so I guess its not a very popular feature (it was at the bottom of my SHACL-AF feature todo-list).

Thanks for your offer to help with implementation. I appreciate it. However in this case, I think its probably better that I do it. The SHACL-AF features in PySHACL are implemented in a bit of a weird way, there's a big learning curve to the code patterns. I have already done all of the node-expression code for use in SHACL-Rules and SHACL-Functions, and all of that can be reused in `ExpressionConstraintComponent`. I'll try to get it done asap.

**Comment by gtfierro** [comment]
Totally reasonable! I know how it can get inside a code base :). Thanks for saying you'll look into it

**Comment by ashleysommer** [comment]
Great timing, I've just finished the implementation! It wasn't too hard.
Released: in https://github.com/RDFLib/pySHACL/releases/tag/v0.16.1 (give it a few minutes to propagate up to PyPI)

**Comment by gtfierro** [comment]
Awesome! Can't wait to try it out. Thanks so much!


________________________________
From: Ashley Sommer ***@***.***>
Sent: Thursday, August 19, 2021 8:36:19 AM
To: RDFLib/pySHACL ***@***.***>
Cc: Gabriel Fierro ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [RDFLib/pySHACL] Planned support for ExpressionConstraintComponent? (#91)


Great timing, I've just finished the implementation! It wasn't too hard.
Released: in https://github.com/RDFLib/pySHACL/releases/tag/v0.16.1<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRDFLib%2FpySHACL%2Freleases%2Ftag%2Fv0.16.1&data=04%7C01%7Cgtfierro%40mines.edu%7C005add1a5ca94869784308d9631eb61e%7C997209e009b346239a4d76afa44a675c%7C0%7C0%7C637649805821144616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3TuO1TxgAkkW5V%2Bjj6fmArR1lTlHQRALlENgyhp8tDI%3D&reserved=0> (give it a few minutes to propagate up to PyPI)
