### ISSUE TITLE
pyshacl and rdflib 6.0

### ISSUE THREAD

**Issue by satra** [RDFLib/pySHACL#92]
on conda forge (https://github.com/conda-forge/pyshacl-feedstock/pulls), pyshacl is not passing tests, likely because of changes in rdflib 6.0.

```python
    def test_079():
        shape_g = rdflib.Graph().parse(data=shapes_data, format='turtle')
>       print(shape_g.serialize(format="turtle").decode())
E       AttributeError: 'str' object has no attribute 'decode'
```

**Comment by ashleysommer** [comment]
Hi @satra 
Thanks for pointing this out. Since v0.15.0 on July 20th, PySHACL was already fully compatible with RDFLib 6.0. Unfortunately I recently committed `test_079` code to the repository, which was from a different codebase and did not contain the RDFLib 6.0 update.
I'll rectify that now.

**Comment by ashleysommer** [comment]
That is fixed now. Do I need to push a new release for Conda to ingest the new version?

**Comment by satra** [comment]
> Do I need to push a new release for Conda to ingest the new version?

yes, and that will trigger a new PR, which we can then merge.

**Comment by satra** [comment]
thanks @ashleysommer - i believe this has been released now.
