### ISSUE TITLE
rdflib-jsonld is still a dependency of version 0.17.0

### ISSUE THREAD

**Issue by tcmitchell** [RDFLib/pySHACL#95]
The [release notes for v0.17.0](https://github.com/RDFLib/pySHACL/releases/tag/v0.17.0) imply that rdflib-jsonld is no longer a dependency.  And I see issue #93 ("Remove (soft)dependency on rdflib_jsonld") and merged pull request #94 ("Remove dependency on rdflib-jsonld"). Yet v0.17.0 still lists rdflib-jsonld as a dependency:

```
$ pip show pyshacl
Name: pyshacl
Version: 0.17.0
Summary: Python SHACL Validator
Home-page: https://github.com/RDFLib/pySHACL
Author: Ashley Sommer
Author-email: Ashley.Sommer@csiro.au
License: Apache-2.0
Location: /Users/tmitchel/Projects/sd2/pySBOL3/venv/lib/python3.8/site-packages
Requires: rdflib-jsonld, owlrl, rdflib
Required-by: 
```

It took me quite a while to track down which dependency of mine was including rdflib-jsonld and I was surprised to see, given the recent changes here, that rdflib-jsonld is still listed as a dependency. Should it be?

**Comment by ashleysommer** [comment]
Hi @tcmitchell, you're right, rdflib_jsonld should definitely not be listed as a dependency.
PySHACL releases v0.16.2.post1 and v0.17.0 both changed json-ld to an optional dependency.

See: https://github.com/RDFLib/pySHACL/blob/0a7d0e81c1f3cb1085d400b8badbfa9a7752f43b/pyproject.toml#L58

**Comment by ashleysommer** [comment]
Ok, looks like Poetry doesn't quite support optional extras in that sense. See:
https://github.com/python-poetry/poetry/issues/2749

I'll have to add an extras package that points to it. Easy enough, then I'll do a new release (v0.16.2.post2 and v0.17.0.post2)

**Comment by ashleysommer** [comment]
Ok, versions **v0.16.2.post2** and **v0.17.0.post2** are now published, which resolves that error. Sorry for the mixup.
